
# Task name - used to pick the class to load
task_name: ShadowHandTracking #  ${task.name}
# experiment name. defaults to name of training config
experiment: ''

# if set to positive integer, overrides the default number of environments
num_envs: ''

# seed - set to -1 to choose random seed
seed: 42
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: ''

## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# device for running physics simulation
sim_device: 'cuda:0'
# device to run RL
rl_device: 'cuda:0'

# pipeline: 'cpu'
# # device for running physics simulation
# sim_device: 'cpu'
# # device to run RL
# rl_device: 'cpu'
graphics_device_id: 0

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: False
# used to set checkpoint path
checkpoint: ''
# set sigma when restoring network
sigma: ''
# set to True to use multi-gpu training
multi_gpu: False

wandb_activate: False
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: 'isaacgymenvs'
wandb_tags: []
wandb_logcode_dir: '' 

# capture_video: False
capture_video: True
capture_video_freq: 1464
# capture_video_len: 135
capture_video_len: 300
force_render: True

render_mode: 'ansi'

exp_dir: '.'
tag: 'exp'

# disables rendering
headless: False

# set default task and default training config based on task
defaults:
  - task: ShadowHandTracking
  - train: HumanoidPPO
  - hydra/job_logging: disabled
  - pbt: no_pbt


hydra:
  output_subdir: null
  run:
    dir: .


two_hands: True
scaled_object_asset_file: 'arctic_microwave_wcollision.urdf'
gt_data_fn: './ReferenceData/shadow_arctic_s06_microwave_data_v3_opt2.npy'